SoftMediaLabView/Models/ErrorViewModel.cs
using System;

namespace SoftMediaLabView.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SoftMediaLabView/Models/StudentListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SoftMediaLabView.Models
{
    public class StudentListViewModel
    {
        public List<StudentViewModel> Items { get; set; }
    }
}

SoftMediaLabView/Models/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SoftMediaLabView.Models
{
    public class StudentViewModel
    {
        public StudentViewModel()
        {
            Performances = Enum.GetValues(typeof(Performance))
                .Cast<Performance>()
                .Select(r => new SelectListItem()
                {
                    Text = r.ToString(),
                    Value = r.ToString()
                })
                .ToList();
        }

        public Student Student { get; init; }

        public List<SelectListItem> Performances { get; init; }
    }

    public class Student
    {
        public int Id { get; init; }
        public string FullName { get; init; }
        public DateTime BirthDate { get; init; }
        public string Performance { get; init; }

        public Student()
        {

        }
        public Student(SoftMediaLab.Models.Student student)
        {
            Id = student.Id;
            FullName = student.FullName;
            BirthDate = student.BirthDate.GetValueOrDefault();
            Performance = student.Performance.ToString();
        }
    }

    public enum Performance
    {
        [Description("Неуд")]
        Неуд = 2,
        [Description("Удовлетворительно")]
        Удовлетворительно = 3,
        [Description("Хорошо")]
        Хорошо = 4,
        [Description("Отлично")]
        Отлично = 5
    }
}

SoftMediaLabView/Controllers/StudentViewController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SoftMediaLabView.Models;
using ApiClient;

namespace SoftMediaLabView.Controllers;

[Route("[controller]")]
public class StudentViewController : Controller
{
    private readonly IStudentApiClient _service;

    public StudentViewController(IStudentApiClient service)
    {
        _service = service;
    }

    [HttpGet("{id}")]
    public async Task<IActionResult> Index(int id)
    {
        var model = await _service.GetAsync(id);

        var vm = new StudentViewModel() { Student = new Student(model) };

        return View(vm);
    }

    [HttpGet("/")]
    public async Task<IActionResult> List()
    {
        var items = (await _service.GetAsync())
            .Select(r => new StudentViewModel()
            {
                Student = new Student(r)
            })
            .ToList();

        var model = new StudentListViewModel()
        {
            Items = items
        };

        return View(model);
    }

    [HttpGet("/Delete/{id}")]
    public async Task<ActionResult> Delete(int id)
    {
        await _service.Delete(id);

        return RedirectToAction("List");
    }

    [HttpPost("/Update")]
    public async Task<ActionResult> Update(StudentViewModel model)
    {
        await _service.Update(new SoftMediaLab.Models.StudentViewModel()
        {
            BirthDate = model.Student.BirthDate,
            Id = model.Student.Id,
            FullName = model.Student.FullName,
            Performance = model.Student.Performance
        });

        return RedirectToAction("List");
    }

    [HttpGet("/Create")]
    public ActionResult Create()
    {
        var model = new StudentViewModel()
        {
            Student = new Student()
            {
                Performance = "0",
                BirthDate = DateTime.Now,
                FullName = ""
            }
        };

        return View(model);
    }

    [HttpPost("/Create")]
    public async Task<ActionResult> Create(StudentViewModel model)
    {
        await _service.Create(new SoftMediaLab.Models.StudentViewModel()
        {
            BirthDate = model.Student.BirthDate,
            FullName = model.Student.FullName,
            Performance = model.Student.Performance
        });

        return RedirectToAction("List");
    }
}

SoftMediaLabView/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SoftMediaLabView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoftMediaLabView</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="StudentView" asp-action="List">SoftMediaLabView</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StudentView" asp-action="List">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SoftMediaLabView
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SoftMediaLabView/Views/Student/Create.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="row align-content-center">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Создать
                </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @using (Html.BeginForm("Create", "Student", null, FormMethod.Post))
                    {
                        @Html.HiddenFor(r => Model.Student.Id)
                        <p>
                            @Html.LabelFor(r => Model.Student.FullName)
                            @Html.TextBoxFor(r => Model.Student.FullName, new { @class="form-control" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.BirthDate)
                            @Html.TextBoxFor(r => Model.Student.BirthDate, "{0:yyyy-MM-dd}", new { @class="form-control", @type = "date" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.Performance)
                            @Html.DropDownListFor(r => Model.Student.Performance, Model.Performances, new { @class="form-control" })
                        </p>
                        <p>
                            <input type="submit" class="btn-success btn" value="Сохранить"/>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SoftMediaLabView/Views/Student/Index.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="row align-content-center">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Студент @Model.Student.FullName, №@Model.Student.Id
                </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @using (Html.BeginForm("Update", "Student", null, FormMethod.Post))
                    {
                        @Html.HiddenFor(r => Model.Student.Id)
                        <p>
                            @Html.LabelFor(r => Model.Student.FullName)
                            @Html.TextBoxFor(r => Model.Student.FullName, new { @class="form-control" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.BirthDate)
                            @Html.TextBoxFor(r => Model.Student.BirthDate, "{0:yyyy-MM-dd}", new { @class="form-control", @type="date" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.Performance)
                            @Html.DropDownListFor(r => Model.Student.Performance, Model.Performances, new { @class="form-control" })
                        </p>
                        <p>
                            <input type="submit" value="Сохранить" class="btn btn-success"/>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SoftMediaLabView/Views/Student/List.cshtml
@model StudentListViewModel
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

@foreach (var it in Model.Items)
{
    <p>@it.Student.FullName</p>
}

<div class="row align-content-center">
    <div class="col-md-12">
        @Html.ActionLink("Создать", "Create", "Student", null, new { @class="btn btn-success" })
        <table class="table table-bordered table-hover table-info">
            <thead>
            <tr>
                <th>Id</th>
                <th>ФИО</th>
                <th>Дата рождения</th>
                <th>Успеваемость</th>
                <th>X</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var it in Model.Items)
            {
                <tr>
                    <td>@Html.ActionLink(it.Student.Id.ToString(), "Index", "Student", new {@id = it.Student.Id})</td>
                    <td>@it.Student.FullName</td>
                    <td>@it.Student.BirthDate.ToShortDateString()</td>
                    <td>@it.Student.Performance</td>
                    <td>@Html.ActionLink("Удалить", "Delete", "Student", new {@id = it.Student.Id}, new {@class = "btn btn-danger"})</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

SoftMediaLabView/Views/StudentView/Create.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="row align-content-center">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Создать
                </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @using (Html.BeginForm("Create", "StudentView", null, FormMethod.Post))
                    {
                        @Html.HiddenFor(r => Model.Student.Id)
                        <p>
                            @Html.LabelFor(r => Model.Student.FullName)
                            @Html.TextBoxFor(r => Model.Student.FullName, new { @class="form-control" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.BirthDate)
                            @Html.TextBoxFor(r => Model.Student.BirthDate, "{0:yyyy-MM-dd}", new { @class="form-control", @type = "date" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.Performance)
                            @Html.DropDownListFor(r => Model.Student.Performance, Model.Performances, new { @class="form-control" })
                        </p>
                        <p>
                            <input type="submit" class="btn-success btn" value="Сохранить"/>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SoftMediaLabView/Views/StudentView/Index.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Index";
}

<div class="row align-content-center">
    <div class="col-md-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Студент @Model.Student.FullName, №@Model.Student.Id
                </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @using (Html.BeginForm("Update", "StudentView", null, FormMethod.Post))
                    {
                        @Html.HiddenFor(r => Model.Student.Id)
                        <p>
                            @Html.LabelFor(r => Model.Student.FullName)
                            @Html.TextBoxFor(r => Model.Student.FullName, new { @class="form-control" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.BirthDate)
                            @Html.TextBoxFor(r => Model.Student.BirthDate, "{0:yyyy-MM-dd}", new { @class="form-control", @type="date" })
                        </p>
                        <p>
                            @Html.LabelFor(r => Model.Student.Performance)
                            @Html.DropDownListFor(r => Model.Student.Performance, Model.Performances, new { @class="form-control" })
                        </p>
                        <p>
                            <input type="submit" value="Сохранить" class="btn btn-success"/>
                        </p>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

SoftMediaLabView/Views/StudentView/List.cshtml
@model StudentListViewModel
@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<div class="row align-content-center">
    <div class="col-md-12">
        @Html.ActionLink("Создать", "Create", "StudentView", null, new { @class="btn btn-success" })
        <table class="table table-bordered table-hover table-info">
            <thead>
            <tr>
                <th>Id</th>
                <th>ФИО</th>
                <th>Дата рождения</th>
                <th>Успеваемость</th>
                <th>X</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var it in Model.Items)
            {
                <tr>
                    <td>@Html.ActionLink(it.Student.Id.ToString(), "Index", "StudentView", new {@id = it.Student.Id})</td>
                    <td>@it.Student.FullName</td>
                    <td>@it.Student.BirthDate.ToShortDateString()</td>
                    <td>@it.Student.Performance</td>
                    <td>@Html.ActionLink("Удалить", "Delete", "StudentView", new {@id = it.Student.Id}, new {@class = "btn btn-danger"})</td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>